spring:
  profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client


