spring:
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev #开发环境
  application:
    name: openmall-eureka-dev
---
spring: 
  profiles: test #开发环境
  application:
    name: openmall-eureka-test
