spring:
  profiles:
  active:
  - dev
---
server:
  port: 7001
 
spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client


---

server:
  port: 7001
 
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client
